### ISSUE TITLE
error: 'sqrtf' is not a member of 'std'

### ISSUE THREAD

**Issue by netmindz** [RobTillaart/Statistic#13]
Any idea why I would get this error while trying to use this in a fairly large project (WLED)

In file included from wled00/../usermods/audioreactive_auto/audio_reactive_auto.h:4:0,
                 from wled00/usermods_list.cpp:213:
.pio/libdeps/esp32_4MB_S/Statistic/Statistic.h: In member function 'statistic::Statistic<T, C, _useStdDev>::value_type statistic::Statistic<T, C, _useStdDev>::pop_stdev() const':
.pio/libdeps/esp32_4MB_S/Statistic/Statistic.h:211:12: error: 'sqrtf' is not a member of 'std'
     return std::sqrt( _extra.ssqdif() / _cnt);
            ^
.pio/libdeps/esp32_4MB_S/Statistic/Statistic.h:211:12: note: suggested alternative:
In file included from /home/will/.platformio/packages/framework-arduinoespressif32@src-e9b1fbd6563a55e19ddae15e1fc09589/cores/esp32/esp32-hal.h:34:0,
                 from /home/will/.platformio/packages/framework-arduinoespressif32@src-e9b1fbd6563a55e19ddae15e1fc09589/cores/esp32/Arduino.h:35,
                 from wled00/wled.h:67,
                 from wled00/usermods_list.cpp:1:
/home/will/.platformio/packages/framework-arduinoespressif32@src-e9b1fbd6563a55e19ddae15e1fc09589/tools/sdk/include/newlib/math.h:336:14: note:   'sqrtf'
 extern float sqrtf _PARAMS((float));
              ^
In file included from wled00/../usermods/audioreactive_auto/audio_reactive_auto.h:4:0,
                 from wled00/usermods_list.cpp:213:
.pio/libdeps/esp32_4MB_S/Statistic/Statistic.h: In member function 'statistic::Statistic<T, C, _useStdDev>::value_type statistic::Statistic<T, C, _useStdDev>::unbiased_stdev() const':
.pio/libdeps/esp32_4MB_S/Statistic/Statistic.h:218:12: error: 'sqrtf' is not a member of 'std'
     return std::sqrt( _extra.ssqdif() / (_cnt - 1));
            ^
.pio/libdeps/esp32_4MB_S/Statistic/Statistic.h:218:12: note: suggested alternative:
In file included from /home/will/.platformio/packages/framework-arduinoespressif32@src-e9b1fbd6563a55e19ddae15e1fc09589/cores/esp32/esp32-hal.h:34:0,
                 from /home/will/.platformio/packages/framework-arduinoespressif32@src-e9b1fbd6563a55e19ddae15e1fc09589/cores/esp32/Arduino.h:35,
                 from wled00/wled.h:67,
                 from wled00/usermods_list.cpp:1:
/home/will/.platformio/packages/framework-arduinoespressif32@src-e9b1fbd6563a55e19ddae15e1fc09589/tools/sdk/include/newlib/math.h:336:14: note:   'sqrtf'
 extern float sqrtf _PARAMS((float));
              ^

**Comment by RobTillaart** [comment]
Thanks for the issue.
At first sight I have no clue about the why.
If you compile the examples, do you get the same error when compiling examples?

**Comment by netmindz** [comment]
Adding 

namespace std {
  inline float sqrtf(float n) { return __builtin_sqrtf(n); }
};

before #include "Statistic.h" resolves the error, from a quick hack about in the source, it looks like we are in the #include <cmath>
 branch

**Comment by netmindz** [comment]
Building the examples for the ESP32 on the Ardunio IDE in standard .ino file works, so maybe something about being a platformIO project and .h file ?

**Comment by RobTillaart** [comment]
> Building the examples for the ESP32 on the Ardunio IDE in standard .ino file works, so maybe something about being a platformIO project and .h file ?

Can confirm examples compile with Arduino IDE (1.8.19) without a problem.

I do not use the platformIO myself.

**Comment by RobTillaart** [comment]
Found this piece of code in

https://github.com/dvjcodec/SCG-ATC-722.6/pull/1/files#diff-619b7649421f6735e02a44cb1a047418db9462f023276727fdcc9c22afc2d6be
```cpp
#ifdef ARM_FLOAT
  return sqrtf(2.0*E/W0);
#else
  return sqrt(2.0*E/W0);
#endif
```

That looks like a workaround for sqrtf() / sqrt()
So an  **#ifdef PLATFORMIO** or something could solve it, don't know if such flag is set.

**Comment by RobTillaart** [comment]
Might be useful - https://stackoverflow.com/questions/16974669/using-sqrtf-in-c-undefined-reference-to-sqrtf

**Comment by RobTillaart** [comment]
mmm,

Can you change in the Statistic.h   (around line 75)

```cpp
#if HAVE_STDCXX_CMATH || defined(_GLIBCXX_CMATH)
#include <cmath>
#else
#include <math.h>
//  substitute for std::sqrt functions if not in your tool chain
#undef sqrt
namespace std {
  inline float sqrt(float n) { return __builtin_sqrtf(n); }
  inline double sqrt(double n) { return __builtin_sqrt(n); }
  inline long double sqrt(long double n) { return __builtin_sqrtl(n); }
};
#endif  /*  HAVE_STDCXX_CMATH */
```

to 

```cpp
#if HAVE_STDCXX_CMATH || defined(_GLIBCXX_CMATH)
#include <cmath>
#else
#include <math.h>
//  substitute for std::sqrt functions if not in your tool chain
#undef sqrt
namespace std {
  inline float sqrt(float n) { return __builtin_sqrtf(n); }
  inline double sqrt(double n) { return __builtin_sqrt(n); }
  inline long double sqrt(long double n) { return __builtin_sqrtl(n); }
};

#undef sqrtf
namespace std {
  inline float sqrtf(float n) { return __builtin_sqrtf(n); }
};

#endif  /*  HAVE_STDCXX_CMATH */
```

does it compile then?

**Comment by netmindz** [comment]
can you pop that change on a branch for me to test, please

**Comment by RobTillaart** [comment]
> can you pop that change on a branch for me to test, please

oops missed that request.

**Comment by RobTillaart** [comment]
Created a branch - https://github.com/RobTillaart/Statistic/tree/sqrtf
prepared the branch to become version 1.0.3 if it works.

**Comment by netmindz** [comment]
Does not resolve the issue yet sadly. 

#if HAVE_STDCXX_CMATH || defined(_GLIBCXX_CMATH) 

resolves to true for me, so your change is in the else, so has no impact. It's as if I do have cmath, but not the version you expect

**Comment by RobTillaart** [comment]
That would mean "the patch" should be in the above one?

**Comment by netmindz** [comment]
yeah, your change needs to be inside the if, to the else of

#endif  /*  HAVE_STDCXX_CMATH */

**Comment by RobTillaart** [comment]
So like this?
```cpp
#if HAVE_STDCXX_CMATH || defined(_GLIBCXX_CMATH)
#include <cmath>
#undef sqrtf
namespace std {
  inline float sqrtf(float n) { return __builtin_sqrtf(n); }
};
#else
#include <math.h>
//  substitute for std::sqrt functions if not in your tool chain
#undef sqrt
namespace std {
  inline float sqrt(float n) { return __builtin_sqrtf(n); }
  inline double sqrt(double n) { return __builtin_sqrt(n); }
  inline long double sqrt(long double n) { return __builtin_sqrtl(n); }
};
#endif  /*  HAVE_STDCXX_CMATH */
```

**Comment by netmindz** [comment]
yeah, think that should do the same as my workaround did

**Comment by RobTillaart** [comment]
pushed the change.

**Comment by netmindz** [comment]
Yeah that fixes it now thanks

**Comment by RobTillaart** [comment]
Then I will merge it when time permits.
