### ISSUE TITLE
type_traits for Nano compilation

### ISSUE THREAD

**Issue by Bart-Frog** [RobTillaart/Statistic#16]
Hi,
I cannot compil the exemple Average.ino on Nano (but I can to do that on Uno or on Mega)  and compilation is terminated with this error : " No such file or directory #include <type_traits>"

Is it possible to fix it?

Thank you in advance for any info.

**Comment by RobTillaart** [comment]
Thanks for the issue, 
As time is limited it might possibly be next week before I have time to dive into this.

**Comment by RobTillaart** [comment]
Which Nano board do you use exactly?  
Do you use the IDE to compile?

**Comment by RobTillaart** [comment]
Quick look

Change line 41 in the STatistic.h file to
```cpp
#if defined (ARDUINO_AVR_UNO) || defined(ARDUINO_AVR_LEONARDO) || defined(ARDUINO_AVR_MEGA2560) || defined(ARDUINO_AVR_NANO)
```

Please verify if this fixes it.

**Comment by RobTillaart** [comment]
Solution 2
Change line 41 to

```cpp
#if defined(__AVR__)   // much simpler
```

Please verify this solution too

**Comment by Bart-Frog** [comment]
Perfect, it works now for Nano. Thanks a lot!

**Comment by RobTillaart** [comment]
Do both work?

**Comment by RobTillaart** [comment]
NB the solution should be in the next version, and I prefer (2) as it covers more boards.

**Comment by Bart-Frog** [comment]
Yep, both work :)
